// Generated by ReScript, PLEASE EDIT WITH CARE


var defaultConfig = {
  baseUrl: "https://api.coingecko.com/api/v3",
  timeout: 5000,
  retryAttempts: 3
};

var defaultQueryOptions = {
  cacheDuration: 30,
  forceRefresh: false
};

var rateLimit = 60;

var maxCacheSize = 1000;

var defaultCacheTtl = 30;

var baseUrl = "https://api.coingecko.com/api/v3";

var defaultTimeout = 5000;

var defaultRetryAttempts = 3;

export {
  defaultConfig ,
  defaultQueryOptions ,
  rateLimit ,
  maxCacheSize ,
  defaultCacheTtl ,
  baseUrl ,
  defaultTimeout ,
  defaultRetryAttempts ,
}
/* No side effect */
