// Generated by ReScript, PLEASE EDIT WITH CARE


var defaultConfig = {
  baseUrl: "https://api.exchange.com",
  timeout: 5000,
  retryAttempts: 3
};

var defaultQueryOptions = {
  cacheDuration: 30,
  forceRefresh: false
};

var rateLimit = 60;

var maxCacheSize = 1000;

var defaultCacheTtl = 30;

export {
  defaultConfig ,
  defaultQueryOptions ,
  rateLimit ,
  maxCacheSize ,
  defaultCacheTtl ,
}
/* No side effect */
