// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Api from "./Api.res.mjs";
import * as Utils from "./Utils.res.mjs";
import * as Config from "./Config.res.mjs";
import * as Caml_int32 from "rescript/lib/es6/caml_int32.js";

function make(configOpt, param) {
  var config = configOpt !== undefined ? configOpt : Config.defaultConfig;
  var api = Api.make(config);
  return {
          api: api,
          cache: Utils.Cache.make(Config.defaultCacheTtl, undefined, undefined),
          requestThrottle: Utils.throttle((function () {
                  
                }), Caml_int32.div(60000, Config.rateLimit))
        };
}

function getPrice(client, optionsOpt, param) {
  var options = optionsOpt !== undefined ? optionsOpt : Config.defaultQueryOptions;
  if (options.forceRefresh) {
    client.requestThrottle();
    return Api.getCurrentPrice(client.api).then(function (result) {
                if (result.TAG !== "Ok") {
                  return Promise.resolve(result);
                }
                var data = result._0;
                var match = options.cacheDuration;
                if (match !== undefined) {
                  Utils.Cache.set(client.cache, "BTC/USDT", data);
                }
                return Promise.resolve({
                            TAG: "Ok",
                            _0: data
                          });
              });
  }
  var data = Utils.Cache.get(client.cache, "BTC/USDT");
  if (data !== undefined) {
    return Promise.resolve({
                TAG: "Ok",
                _0: data
              });
  } else {
    client.requestThrottle();
    return Api.getCurrentPrice(client.api).then(function (result) {
                if (result.TAG !== "Ok") {
                  return Promise.resolve(result);
                }
                var data = result._0;
                var match = options.cacheDuration;
                if (match !== undefined) {
                  Utils.Cache.set(client.cache, "BTC/USDT", data);
                }
                return Promise.resolve({
                            TAG: "Ok",
                            _0: data
                          });
              });
  }
}

export {
  make ,
  getPrice ,
}
/* Api Not a pure module */
