// Generated by ReScript, PLEASE EDIT WITH CARE

import * as PriceLib from "./PriceLib.res.mjs";

var client = PriceLib.PriceLib.createClient(undefined, undefined, undefined, undefined);

PriceLib.PriceLib.getPrice(client, "bitcoin", "usd", (function (data) {
        console.log({
              message: "Success",
              data: data
            });
      }), (function (error) {
        console.log({
              message: "Error",
              error: error
            });
      }));

var clientCMC = PriceLib.PriceLib.createClientUrl("https://pro-api.coinmarketcap.com");

PriceLib.PriceLib.getCMCPrice(clientCMC, "BTC", "USD", "8958b1e7-36e6-4335-9ff7-86f9da097128");

export {
  client ,
  clientCMC ,
}
/* client Not a pure module */
